In [1]:
import numpy as np
prime_array = np.array([2,3,5,7,11])
print(prime_array)


[ 2  3  5  7 11]


In [2]:
type(prime_array)

numpy.ndarray

In [4]:
#2D ARRAY

n = np.array([[1,2],[3,4]])
print(n)
n.shape

[[1 2]
 [3 4]]


(2, 2)

In [5]:
#3D ARRAY

m= np.array([[[1,2],[3,4]],
[[5,6],[7,8]]])

print(m)
print(m.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [6]:
array_3d = np.array([
[ # Layer 1
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]
],
[ # Layer 2
[13, 14, 15, 16],
[17, 18, 19, 20],
[21, 22, 23, 24]
]
])
print(array_3d)
print("Shape:", array_3d.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [8]:
import numpy as np

# 1. Create a 1D NumPy array with numbers from 1 to 10.
arr1 = np.arange(1, 11)
print("1.", arr1)

# 2. Create a NumPy array of zeros of size 5.
arr2 = np.zeros(5)
print("2.", arr2)

# 3. Create a NumPy array of ones of size 4 × 4.
arr3 = np.ones((4, 4))
print("3.\n", arr3)

# 4. Create an array of even numbers from 2 to 20.
arr4 = np.arange(2, 21, 2)
print("4.", arr4)

# 5. Create an array with values from 10 to 50, step 5.
arr5 = np.arange(10, 51, 5)
print("5.", arr5)

# 6. Create an array [1, 2, 3] and multiply it by 3.
arr6 = np.array([1, 2, 3]) * 3
print("6.", arr6)

# 7. Create two arrays and add them element-wise.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("7.", a + b)

# 8. Create an array [10, 20, 30, 40] and find its mean.
arr8 = np.array([10, 20, 30, 40])
print("8. Mean =", np.mean(arr8))

# 9. Create an array [4, 9, 16, 25] and find the square root.
arr9 = np.array([4, 9, 16, 25])
print("9.", np.sqrt(arr9))

# 10. Create a random array of size 5 and find its sum.
arr10 = np.random.rand(5)
print("10. Array =", arr10)
print("    Sum =", np.sum(arr10))

# 11. Slice the first 5 elements from an array of numbers from 1 to 10.
arr11 = np.arange(1, 11)
print("11.", arr11[:5])

# 12. Get the last two elements of [10, 20, 30, 40, 50].
arr12 = np.array([10, 20, 30, 40, 50])
print("12.", arr12[-2:])

# 13. Change the 3rd element of [1, 2, 3, 4, 5] to 99.
arr13 = np.array([1, 2, 3, 4, 5])
arr13[2] = 99
print("13.", arr13)

# 14. Create a 3×3 matrix and access the element in the 2nd row, 3rd column.
arr14 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("14. Matrix:\n", arr14)
print("    Element =", arr14[1, 2])

# 15. Create a 1D array and reverse it using slicing.
arr15 = np.array([1, 2, 3, 4, 5])
print("15.", arr15[::-1])

1. [ 1  2  3  4  5  6  7  8  9 10]
2. [0. 0. 0. 0. 0.]
3.
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
4. [ 2  4  6  8 10 12 14 16 18 20]
5. [10 15 20 25 30 35 40 45 50]
6. [3 6 9]
7. [5 7 9]
8. Mean = 25.0
9. [2. 3. 4. 5.]
10. Array = [0.38408687 0.06797567 0.04212389 0.4331642  0.92580253]
    Sum = 1.8531531519774935
11. [1 2 3 4 5]
12. [40 50]
13. [ 1  2 99  4  5]
14. Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    Element = 6
15. [5 4 3 2 1]


In [9]:

# 16. Generate a random integer between 1 and 100.
print("16.", np.random.randint(1, 101))

# 17. Generate a random array of size 3 × 3.
arr17 = np.random.rand(3, 3)
print("17.\n", arr17)

# 18. Generate 5 random numbers from a normal distribution.
arr18 = np.random.randn(5)
print("18.", arr18)

# 19. Generate 10 random numbers between 0 and 1.
arr19 = np.random.rand(10)
print("19.", arr19)

# 20. Shuffle an array [1, 2, 3, 4, 5] randomly.
arr20 = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr20)
print("20.", arr20)

# 21. Transpose a 2×3 matrix.
arr21 = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("21. Original:\n", arr21)
print("    Transpose:\n", arr21.T)

# 22. Reshape a 1D array (1 to 12) into 3×4.
arr22 = np.arange(1, 13).reshape(3, 4)
print("22.\n", arr22)

# 23. Resize a 1D array of size 5 into 3×3.
arr23 = np.array([1, 2, 3, 4, 5])
print("23.\n", np.resize(arr23, (3, 3)))

# Zero-padding alternative
arr23_pad = np.zeros(9, dtype=int)
arr23_pad[:5] = arr23
print("    Zero-padded:\n", arr23_pad.reshape(3, 3))

# 24. Convert a 2D array into 1D.
arr24 = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("24.", arr24.flatten())

16. 21
17.
 [[0.53783546 0.35890853 0.82906014]
 [0.13073974 0.08372317 0.60499887]
 [0.81646087 0.38747407 0.83704333]]
18. [ 1.03176813 -0.45516632  0.15817582  1.2391092   0.87508575]
19. [0.87259594 0.10411671 0.68033541 0.31508538 0.39246371 0.45160163
 0.58479883 0.49190044 0.27474271 0.85084497]
20. [4 2 1 5 3]
21. Original:
 [[1 2 3]
 [4 5 6]]
    Transpose:
 [[1 4]
 [2 5]
 [3 6]]
22.
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
23.
 [[1 2 3]
 [4 5 1]
 [2 3 4]]
    Zero-padded:
 [[1 2 3]
 [4 5 0]
 [0 0 0]]
24. [1 2 3 4 5 6]
