In [3]:
import numpy as np
arry = np.arange(1,10)
arry

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import numpy as np 
ary = np.random.randint(10,30,(4,5))
ary


array([[25, 23, 16, 18, 18],
       [23, 13, 20, 26, 20],
       [12, 15, 16, 23, 18],
       [24, 14, 26, 21, 20]], dtype=int32)

In [5]:
a =np.random.random(5)
print(a)
b = np.random.randn(5)
print(b)


[0.99682185 0.26879719 0.41187862 0.80709795 0.55260611]
[-0.54577959  2.54028713 -0.7348731   1.58640556  0.56889008]


In [6]:
print(ary[0:1])

[[25 23 16 18 18]]


In [7]:
print(ary[:,-1:])

[[18]
 [20]
 [18]
 [20]]


In [8]:
new = (5,4)
new_shape = np.reshape(ary,new)
print(new_shape)


[[25 23 16 18]
 [18 23 13 20]
 [26 20 12 15]
 [16 23 18 24]
 [14 26 21 20]]


In [9]:
new = (2,5,2)
new_shap = np.reshape(ary,new)
print(new_shap)

[[[25 23]
  [16 18]
  [18 23]
  [13 20]
  [26 20]]

 [[12 15]
  [16 23]
  [18 24]
  [14 26]
  [21 20]]]


In [10]:
import pandas as pd
data = {"employee" :["sudhi","rajeev","athul"],
        'income': [6000,4000,5000]
        }

emplyee = pd.DataFrame(data,index = ["a","b","c"])
print(emplyee)

  employee  income
a    sudhi    6000
b   rajeev    4000
c    athul    5000


In [11]:
arryr = pd.DataFrame(ary, index = ["a","b","c","d"],columns = ["A","B","C","D","E"])
arryr



,A,B,C,D,E
a,25,23,16,18,18
b,23,13,20,26,20
c,12,15,16,23,18
d,24,14,26,21,20


In [12]:
arryr = pd.DataFrame(ary , index = ["a","b","c","d"],columns = ["Name","B","C","D","E"])
arryr

,Name,B,C,D,E
a,25,23,16,18,18
b,23,13,20,26,20
c,12,15,16,23,18
d,24,14,26,21,20


In [14]:
arryr.to_csv("arryr.csv",index =False)


In [17]:
%pip install openpyxl



arryr.to_excel("arryr.xlsx", index = False)

You should consider upgrading via the 'c:\Users\SUDHI S R\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


     ------------------------------------ 250.9/250.9 KB 771.4 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
'''Create a DataFrame from a dictionary containing Name and Age.'''

import pandas as pd
data = {"employee" :["sudhi","rajeev","athul"],
        'Age': [24,25,23]
        }

student = pd.DataFrame(data)
print(student)

  employee  Age
0    sudhi   24
1   rajeev   25
2    athul   23


In [2]:
'''Create a DataFrame from a list of lists containing student details'''

list_of_lists = [['Amar', 'Amar nivas mumbai',27], ['Akbar', 'Haji street mumbai',24], ['Anthony', 'Jesus christ road mumbai',25]]
df = pd.DataFrame(list_of_lists, columns = ['Name','Address', 'Age'])
df

,Name,Address,Age
0,Amar,Amar nivas mumbai,27
1,Akbar,Haji street mumbai,24
2,Anthony,Jesus christ road mumbai,25


In [4]:
'''Create a DataFrame from a list of tuples'''

names = ['Arun ','Bharath', 'suraj']
profession = ['IT Employee','Business','Actor']

list_tuple = list(zip(names,profession))
df = pd.DataFrame(list_tuple,columns = ['Name','Profession'])
print(list_tuple)
print(df)

[('Arun ', 'IT Employee'), ('Bharath', 'Business'), ('suraj', 'Actor')]
      Name   Profession
0    Arun   IT Employee
1  Bharath     Business
2    suraj        Actor


In [6]:
'''Create a DataFrame from a NumPy array.'''

import numpy as np
a =np.random.randint(1,10,(4,5))
sf = pd.DataFrame(a, columns =['A','B','C','D','E'])
sf

,A,B,C,D,E
0,4,5,2,6,9
1,2,4,8,7,9
2,6,4,4,4,9
3,9,7,9,7,6


In [7]:
'''Create a DataFrame with custom row labels.'''
data = {
    "Name": ["John", "Emma", "Alice"],
    "Age": [22, 21, 23]
}

df = pd.DataFrame(data, index=["A", "B", "C"])
print(df)

    Name  Age
A   John   22
B   Emma   21
C  Alice   23


In [8]:
'''Create an empty DataFrame.'''

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [9]:
'''Create a DataFrame with only one column named Marks.'''
df = pd.DataFrame({
    "Marks": [85, 90, 78, 88]
})

print(df)

   Marks
0     85
1     90
2     78
3     88


In [ ]:
'''Create a DataFrame using two Pandas Series.'''

name = pd.Series(["John", "Emma", "Alice"])
age = pd.Series([22, 21, 23])

df = pd.DataFrame({
    "Name": name,
    "Age": age
})

print(df)

    Name  Age
0   John   22
1   Emma   21
2  Alice   23


In [11]:
'''Create a DataFrame with three columns: ID, Name, and Department'''

data = {
    "ID": [101, 102, 103],
    "Name": ["John", "Emma", "Alice"],
    "Department": ["CSE", "ECE", "ME"]
}

df = pd.DataFrame(data)
print(df)

    ID   Name Department
0  101   John        CSE
1  102   Emma        ECE
2  103  Alice         ME


In [12]:
'''Create a DataFrame containing five students and their marks'''

data = {
    "Student": ["John", "Emma", "Alice", "David", "Bob"],
    "Marks": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)
print(df)


  Student  Marks
0    John     85
1    Emma     90
2   Alice     78
3   David     88
4     Bob     92


In [13]:
'''Create a DataFrame with 10 rows and 4 columns filled with zeros.'''
df = pd.DataFrame(
    np.zeros((10, 4)),
    columns=["A", "B", "C", "D"]
)

print(df)

     A    B    C    D
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0
7  0.0  0.0  0.0  0.0
8  0.0  0.0  0.0  0.0
9  0.0  0.0  0.0  0.0


In [14]:
'''Create a DataFrame with 5 rows and 3 columns filled with ones.'''

df = pd.DataFrame(
    np.ones((5, 3)),
    columns=["A", "B", "C"]
)

print(df)

     A    B    C
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0


In [15]:
'''Create a DataFrame with values from 1 to 20 arranged into 5 rows and 4 columns.'''

data = np.arange(1, 21).reshape(5, 4)

df = pd.DataFrame(
    data,
    columns=["A", "B", "C", "D"]
)

print(df)

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [16]:
'''Create a DataFrame with mixed data types (integer, string, float, boolean).'''

data = {
    "ID": [101, 102, 103],
    "Name": ["John", "Emma", "Alice"],
    "Percentage": [85.5, 90.0, 78.25],
    "Passed": [True, True, False]
}

df = pd.DataFrame(data)

print(df)

    ID   Name  Percentage  Passed
0  101   John       85.50    True
1  102   Emma       90.00    True
2  103  Alice       78.25   False
